"use strict";
// Optional local integration check. Requires Playwright and a running
// tests/feedback_smoke_server.py fixture; never point this at a real deployment.
const { chromium } = require("playwright");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const base = process.argv[2];
if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(base || "")) throw new Error("A local smoke fixture URL is required");
const output = path.resolve(__dirname, "../.test-tmp/feedback-browser");
fs.mkdirSync(output, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true,
    ...(process.env.ECE329_SMOKE_BROWSER ? { executablePath: process.env.ECE329_SMOKE_BROWSER } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  context.on("page", page => page.on("pageerror", error => errors.push(error.message)));
  try {
    const page = await context.newPage();
    await page.goto(base);
    await page.locator("#feedbackButton").click();
    assert.equal(await page.locator("#feedbackClose").evaluate(el => getComputedStyle(el).color), "rgb(20, 45, 66)");
    await page.locator("#feedbackStatus").filter({ hasText: "请先连接课程服务" }).waitFor();
    assert.equal(await page.locator("#feedbackSubmit").isDisabled(), true);
    await page.locator("#feedbackClose").click();
    const ids = [];
    for (const mode of ["GUIDED_DESIGN", "EMVR_DIRECT"]) {
      const response = await context.request.post(`${base}/v1/designs`, { data: { idea: "我想研究磁场实验", interaction_state: mode } });
      assert.equal(response.status(), 201);
      const design = await response.json();
      ids.push(design.design_id);
      await page.evaluate(design => { invalidateDesignRequests(); applyDesignSnapshot(design); saveState(); render(); }, design);
      await page.locator("#feedbackButton").click();
      await page.locator("#feedbackCategory").selectOption("answered_pending");
      await page.locator("#feedbackMessage").fill(`${mode}：我已经回答过了，为什么重复询问？`);
      await page.locator("#feedbackSubmit").click();
      await page.locator("#feedbackStatus").filter({ hasText: /^提交成功：/ }).waitFor();
      await page.locator("#feedbackRefresh").click();
      await page.locator("#feedbackHistory").filter({ hasText: mode === "GUIDED_DESIGN" ? "已生成经验" : "同类经验" }).waitFor();
      const records = await (await context.request.get(`${base}/v1/designs/${design.design_id}/feedback`, { headers: { Authorization: `Bearer ${design.design_access_token}` } })).json();
      assert.equal(records.feedback.length, 1);
      assert.equal(records.feedback[0].durable, true);
      assert.equal(records.feedback[0].max_attempts, 10);
      assert.match(await page.locator('#feedbackHistory').innerText(), /分析 1\/10 次/);
      const unchanged = await (await context.request.get(`${base}/v1/designs/${design.design_id}`, { headers: { Authorization: `Bearer ${design.design_access_token}` } })).json();
      assert.equal(unchanged.revision, design.revision);
      await page.screenshot({ path: path.join(output, `${mode}.png`) });
      await page.locator("#feedbackClose").click();
    }
    const admin = await context.newPage();
    await admin.goto(`${base}/feedback-review.html`);
    assert.deepEqual(await admin.locator('#reviewFilter optgroup').nth(1).locator('option').evaluateAll(options=>options.map(o=>o.value)), ['candidate','active','stopped']);
    await admin.locator("#reviewToken").fill("wrong-token");
    const denied = new Promise(resolve=>admin.once('dialog',async dialog=>{assert.equal(dialog.message(),'密码错误');await dialog.accept();resolve();}));
    await admin.locator("#reviewLogin button[type=submit]").click();
    await denied;
    await admin.locator("#reviewToken").fill("smoke-maintainer");
    await admin.locator("#reviewLogin button[type=submit]").click();
    await admin.locator('#reviewStatus').filter({hasText:'反馈总数：2'}).waitFor();
    assert.equal(await admin.locator('.experience-card').count(),2);
    await admin.locator('#reviewFilter').selectOption('candidate');
    await admin.locator('#reviewLogin button[type=submit]').click();
    const candidates = await (await context.request.get(`${base}/v1/feedback/experiences?status=candidate`, { headers: { "X-ECE329-Feedback-Admin-Token": "smoke-maintainer" } })).json();
    const candidate = candidates.experiences.find(item => item.evidence.scope_design_id === ids[0]);
    assert.ok(candidate, "Find this test's candidate, even when other scoped experiences exist");
    const card = admin.locator(".experience-card").filter({ has: admin.locator(`[id="scope-${candidate.id}"]`) });
    await card.waitFor();
    await card.getByRole("button", { name: "启用经验", exact: true }).click();
    await admin.locator('#reviewStatus').filter({hasText:'请填写处理意见'}).waitFor();
    assert.equal(await card.locator('textarea[id^=original-]').getAttribute('readonly'), null);
    assert.equal(await card.locator('textarea[id^=original-]').inputValue(), '');
    assert.equal(await card.locator('textarea[id^=corrected-]').inputValue(), '');
    assert.equal(await card.locator('select[id^=correction-field-]').count(), 0);
    const correctedSummary = '上一轮已邀请用户确认继续时，应承接确认并推进对应事项；真实阻塞需说明。';
    const correctedTrigger = '上一轮明确邀请确认继续，用户随后回复继续下一步。';
    const originalNotes = `summary: ${candidate.content.summary}\ntrigger: ${candidate.content.trigger}`;
    await card.locator('textarea[id^=original-]').fill(originalNotes);
    await card.locator('textarea[id^=corrected-]').fill(`summary: ${correctedSummary}\ntrigger: ${correctedTrigger}`);
    assert.deepEqual(JSON.parse(await card.locator('textarea[id^=content-]').inputValue()), candidate.content);
    await card.locator('textarea[id^=content-]').fill(JSON.stringify({...candidate.content, summary:correctedSummary, trigger:correctedTrigger},null,2));
    await card.locator("textarea[id^=note-]").fill("修改后采用；核对适用范围，未进行真实模型回放。");
    await card.getByRole("button", { name: "启用经验", exact: true }).click();
    await admin.locator("#reviewStatus").filter({ hasText: "已保存：已启用" }).waitFor();
    await admin.locator("#reviewFilter").selectOption("active");
    await admin.locator("#reviewLogin button[type=submit]").click();
    await card.getByRole("button", { name: "停止经验", exact: true }).waitFor();
    await admin.screenshot({ path: path.join(output, "review-active.png"), fullPage: true });
    const active = await (await context.request.get(`${base}/v1/feedback/experiences?status=active`, { headers: { "X-ECE329-Feedback-Admin-Token": "smoke-maintainer" } })).json();
    assert.ok(active.experiences.some(item => item.id === candidate.id));
    const enabled = active.experiences.find(item => item.id === candidate.id);
    assert.equal(enabled.content.summary, correctedSummary);
    assert.equal(enabled.content.trigger, correctedTrigger);
    assert.equal(JSON.parse(enabled.reviews[0].note).original, originalNotes);
    await admin.locator('#languageToggle').click();
    await admin.locator('optgroup[label="Experience status"]').waitFor({state:'attached'});
    await card.getByText('1. Inappropriate agent text (enter manually; may cover multiple fields; leave blank if no correction is needed)', {exact:true}).waitFor();
    await admin.locator('#languageToggle').click();
    await card.getByText('1. Agent 原不恰当内容（请手动填写，可涉及多个字段；无需修改时留空）', {exact:true}).waitFor();
    await card.locator("textarea[id^=corrected-]").fill(await card.locator("textarea[id^=original-]").inputValue());
    await card.locator("textarea[id^=note-]").fill("停用回归：确认后续检索撤回这条经验。");
    await card.getByRole("button", { name: "停止经验", exact: true }).click();
    await admin.locator("#reviewStatus").filter({ hasText: "已保存：已停止" }).waitFor();
    await admin.locator("#reviewFilter").selectOption("stopped");
    await admin.locator("#reviewLogin button[type=submit]").click();
    await card.getByRole("button", {name:"重新启用",exact:true}).waitFor();
    assert.equal(await card.locator('textarea[id^=content-]').isEditable(), true);
    assert.equal(await card.getByRole('button',{name:'停止经验',exact:true}).count(),0);
    const revised = JSON.parse(await card.locator('textarea[id^=content-]').inputValue());
    revised.verification = '确认后推进具体事项，不重复已回答问题。';
    await card.locator('textarea[id^=content-]').fill(JSON.stringify(revised,null,2));
    assert.equal(await card.locator('textarea[id^=original-]').inputValue(), '');
    assert.equal(await card.locator('textarea[id^=corrected-]').inputValue(), '');
    await card.locator('textarea[id^=note-]').fill('批准');
    await card.getByRole("button", {name:"重新启用",exact:true}).click();
    await admin.locator("#reviewStatus").filter({hasText:"已保存：已启用"}).waitFor();
    const restored = await (await context.request.get(`${base}/v1/feedback/experiences?status=active`, {headers:{"X-ECE329-Feedback-Admin-Token":"smoke-maintainer"}})).json();
    const restoredItem = restored.experiences.find(item=>item.id===candidate.id);
    assert.equal(restoredItem.content.verification,revised.verification);
    assert.deepEqual(restoredItem.reviews.map(r=>r.decision),['approve','stop','approve']);
    const inbox = await (await context.request.get(`${base}/v1/feedback/tickets`, {headers:{"X-ECE329-Feedback-Admin-Token":"smoke-maintainer"}})).json();
    assert.deepEqual(inbox.counts,{candidate:1,duplicate:1});
    assert.ok(inbox.feedback.every(item=>item.experience.status==='active'));
    await admin.locator("#reviewLogout").click();
    assert.equal(await admin.locator("#reviewToken").inputValue(), "");
    assert.equal(await admin.evaluate(() => Object.keys(localStorage).some(key => localStorage[key].includes("smoke-maintainer"))), false);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator("#feedbackButton").click();
    await page.screenshot({ path: path.join(output, "mobile.png") });
    const bounds = await page.locator("#feedbackDialog").boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ passed: true, designs: ids, checks: "both modes, real SQLite receipts, no stage advancement, three experience states, stop/edit/re-enable, separate feedback outcomes, bilingual filters, admin denial/approval, no stored admin token, mobile dialog", screenshots: output }));
  } catch (error) {
    for (const [index, page] of context.pages().entries()) {
      await page.screenshot({ path: path.join(output, `failure-${index}.png`) }).catch(() => {});
      console.error(await page.locator("#feedbackStatus, #reviewStatus").allTextContents());
    }
    throw error;
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
